
name: Convert Image to SVG with Inkscape

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  vectorize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Inkscape
        run: sudo apt update && sudo apt install -y inkscape

      - name: Convert image to SVG
        run: |
          # Rename file to avoid issues with spaces
          mv "Generated Image July 26, 2025 - 2_25PM.jpeg" input.jpeg
          inkscape input.jpeg --export-plain-svg=output.svg

      - name: Upload SVG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: traced-svg
          path: output.svg
