
name: Render video (Revideo)

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Render video
        run: npm run render

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: out-video
          path: out/video.mp4
          if-no-files-found: error
